import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import { Container } from 'react-bootstrap';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <h1>index를 메인페이지로 만들어야하나 아님 pages안에 따로 만들어야하나 고민중</h1>
      </Wrapper>
    </Container>
  );
};

const Wrapper = styled.div`
  width: 500px;
  height: 200px;
  background-color: gold;
  text-align: center;
  margin: 0 auto;
`;

export default Home;
